#!/bin/sh

# Usage

if [ $# -ne 1 ]
then
   echo "Usage $0 filename.explor"
   exit 2             	
fi

# Create filenames

EXECUTABLE_FILE="$(echo ${1} | sed s/\.explor//)"
PS_FILE="$(echo ${1} | sed s/\.explor/.ps/)"

# Wrap Explor program in Fortran

echo "Compiling ${1} to ${EXECUTABLE_FILE}"


# Compile and run
# "cat $1 end.f" adds END to the program, as explor listings don't have it

(cat "${1}" /usr/local/share/explor/end.f | gfortran -xf77 -o "${EXECUTABLE_FILE}" \
    -L/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -lexplor -) && \
(echo "Running $EXECUTABLE_FILE with output to $PS_FILE") && \
("$(pwd)/${EXECUTABLE_FILE}" > "${PS_FILE}") && \
(echo "Converting $PS_FILE to PDF") && \
(ps2pdf "${PS_FILE}")
