#!/bin/sh

# Usage

if [ $# -ne 1 ]
then
   echo "Usage $0 filename.explor"
   exit 2             	
fi

# Create filenames

FORTRAN_FILE=$(echo $1 | sed s/\.explor/.f/)
#OBJECT_FILE=$(echo $1 | sed s/\.explor/.o/)
EXECUTABLE_FILE=$(echo $1 | sed s/\.explor//)
OUTPUT_FILE=$(echo $1 | sed s/\.explor/.ps/)

# Wrap Explor program in Fortran

echo "Compiling $1 to $EXECUTABLE_FILE"

echo "\
      program explor
      call initexplor
$(cat $1)
      end
" > $FORTRAN_FILE

# Compile and run
# mini-explor.f should be a library...

(gfortran -combine -o $EXECUTABLE_FILE \
    /usr/local/share/explor/mini-explor.f $FORTRAN_FILE) && \
(echo "Running $EXECUTABLE_FILE with output to $OUTPUT_FILE") && \
($EXECUTABLE_FILE > $OUTPUT_FILE)
